//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monobjc.Tools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monobjc.Tools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] Info_001 {
            get {
                object obj = ResourceManager.GetObject("Info_001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Info_002 {
            get {
                object obj = ResourceManager.GetObject("Info_002", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Info_004 {
            get {
                object obj = ResourceManager.GetObject("Info_004", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Info_005 {
            get {
                object obj = ResourceManager.GetObject("Info_005", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Info_010 {
            get {
                object obj = ResourceManager.GetObject("Info_010", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MainMenu_001 {
            get {
                object obj = ResourceManager.GetObject("MainMenu_001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MainMenu_002 {
            get {
                object obj = ResourceManager.GetObject("MainMenu_002", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MainMenu_003 {
            get {
                object obj = ResourceManager.GetObject("MainMenu_003", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MainMenu_004 {
            get {
                object obj = ResourceManager.GetObject("MainMenu_004", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MainMenu_005 {
            get {
                object obj = ResourceManager.GetObject("MainMenu_005", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MainMenu_006 {
            get {
                object obj = ResourceManager.GetObject("MainMenu_006", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MainMenu_007 {
            get {
                object obj = ResourceManager.GetObject("MainMenu_007", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MainMenu_008 {
            get {
                object obj = ResourceManager.GetObject("MainMenu_008", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MainMenu_010 {
            get {
                object obj = ResourceManager.GetObject("MainMenu_010", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MainMenu_011 {
            get {
                object obj = ResourceManager.GetObject("MainMenu_011", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MainMenu_012 {
            get {
                object obj = ResourceManager.GetObject("MainMenu_012", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MyDocument_005 {
            get {
                object obj = ResourceManager.GetObject("MyDocument_005", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
