#!/bin/bash

for f in `ls Work`; do
	cat Work/$f	\
		| sed -e "s/AVAILABLE_WEBKIT_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_WEBKIT_VERSION_3_0//g" \
		| sed -e "s/AVAILABLE_WEBKIT_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_WEBKIT_VERSION_4_0//g" \
		| sed -e "s/AVAILABLE_WEBKIT_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_WEBKIT_VERSION_3_0//g" \
		| sed -e "s/AVAILABLE_WEBKIT_VERSION_3_0_AND_LATER//g" \
		| sed -e "s/AVAILABLE_WEBKIT_VERSION_3_0_AND_LATER_BUT_DEPRECATED//g" \
		| sed -e "s/AVAILABLE_IN_WEBKIT_VERSION_4_0//g" \
		| sed -e "s/WEBKIT_OBJC_METHOD_ANNOTATION()//g" \
		| sed -e "s/WEBKIT_VERSION_MAX_ALLOWED >= WEBKIT_VERSION_1_3/1/g" \
		| sed -e "s/WEBKIT_VERSION_MAX_ALLOWED >= WEBKIT_VERSION_3_0/1/g" \
		| sed -e "s/WEBKIT_VERSION_MAX_ALLOWED >= WEBKIT_VERSION_4_0/1/g" \
		| sed -e "s/WEBKIT_VERSION_MAX_ALLOWED >= WEBKIT_VERSION_LATEST/1/g" \
		> Work/$f.tmp
	mv Work/$f.tmp Work/$f
done
