//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.3615
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Monobjc.Tools.Doxygenator.Model {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("doxygen", Namespace="", IsNullable=false)]
    public partial class DoxygenType {
        
        private compounddefType[] compounddefField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("compounddef", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public compounddefType[] compounddef {
            get {
                return this.compounddefField;
            }
            set {
                this.compounddefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class compounddefType {
        
        private string compoundnameField;
        
        private string titleField;
        
        private compoundRefType[] basecompoundrefField;
        
        private compoundRefType[] derivedcompoundrefField;
        
        private incType[] includesField;
        
        private incType[] includedbyField;
        
        private string idField;
        
        private DoxCompoundKind kindField;
        
        private bool kindFieldSpecified;
        
        private DoxProtectionKind protField;
        
        private bool protFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string compoundname {
            get {
                return this.compoundnameField;
            }
            set {
                this.compoundnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("basecompoundref", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public compoundRefType[] basecompoundref {
            get {
                return this.basecompoundrefField;
            }
            set {
                this.basecompoundrefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("derivedcompoundref", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public compoundRefType[] derivedcompoundref {
            get {
                return this.derivedcompoundrefField;
            }
            set {
                this.derivedcompoundrefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("includes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public incType[] includes {
            get {
                return this.includesField;
            }
            set {
                this.includesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("includedby", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public incType[] includedby {
            get {
                return this.includedbyField;
            }
            set {
                this.includedbyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DoxCompoundKind kind {
            get {
                return this.kindField;
            }
            set {
                this.kindField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool kindSpecified {
            get {
                return this.kindFieldSpecified;
            }
            set {
                this.kindFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DoxProtectionKind prot {
            get {
                return this.protField;
            }
            set {
                this.protField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool protSpecified {
            get {
                return this.protFieldSpecified;
            }
            set {
                this.protFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class compoundRefType {
        
        private string refidField;
        
        private DoxProtectionKind protField;
        
        private bool protFieldSpecified;
        
        private DoxVirtualKind virtField;
        
        private bool virtFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string refid {
            get {
                return this.refidField;
            }
            set {
                this.refidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DoxProtectionKind prot {
            get {
                return this.protField;
            }
            set {
                this.protField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool protSpecified {
            get {
                return this.protFieldSpecified;
            }
            set {
                this.protFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DoxVirtualKind virt {
            get {
                return this.virtField;
            }
            set {
                this.virtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool virtSpecified {
            get {
                return this.virtFieldSpecified;
            }
            set {
                this.virtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum DoxProtectionKind {
        
        /// <remarks/>
        @public,
        
        /// <remarks/>
        @protected,
        
        /// <remarks/>
        @private,
        
        /// <remarks/>
        package,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum DoxVirtualKind {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("non-virtual")]
        nonvirtual,
        
        /// <remarks/>
        @virtual,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("pure-virtual")]
        purevirtual,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class incType {
        
        private string refidField;
        
        private DoxBool localField;
        
        private bool localFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string refid {
            get {
                return this.refidField;
            }
            set {
                this.refidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DoxBool local {
            get {
                return this.localField;
            }
            set {
                this.localField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool localSpecified {
            get {
                return this.localFieldSpecified;
            }
            set {
                this.localFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum DoxBool {
        
        /// <remarks/>
        yes,
        
        /// <remarks/>
        no,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum DoxCompoundKind {
        
        /// <remarks/>
        @class,
        
        /// <remarks/>
        @struct,
        
        /// <remarks/>
        union,
        
        /// <remarks/>
        @interface,
        
        /// <remarks/>
        protocol,
        
        /// <remarks/>
        category,
        
        /// <remarks/>
        exception,
        
        /// <remarks/>
        file,
        
        /// <remarks/>
        @namespace,
        
        /// <remarks/>
        group,
        
        /// <remarks/>
        page,
        
        /// <remarks/>
        example,
        
        /// <remarks/>
        dir,
    }
}
