//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monobjc.Tools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monobjc.Tools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command returned: {0}.
        /// </summary>
        internal static string CommandReturned {
            get {
                return ResourceManager.GetString("CommandReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found a valid revision : {0}.
        /// </summary>
        internal static string FoundValidRevision {
            get {
                return ResourceManager.GetString("FoundValidRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IB file &apos;{0}&apos; is up-to-date..
        /// </summary>
        internal static string IBFileUpToDate {
            get {
                return ResourceManager.GetString("IBFileUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE plist PUBLIC &quot;-//Apple//DTD PLIST 1.0//EN&quot; &quot;http://www.apple.com/DTDs/PropertyList-1.0.dtd&quot;&gt;
        ///&lt;plist version=&quot;1.0&quot;&gt;
        ///&lt;dict&gt;
        ///	&lt;key&gt;CFBundleDevelopmentRegion&lt;/key&gt;
        ///	&lt;string&gt;English&lt;/string&gt;
        ///	&lt;key&gt;CFBundleExecutable&lt;/key&gt;
        ///	&lt;string&gt;${}&lt;/string&gt;
        ///	&lt;key&gt;CFBundleIconFile&lt;/key&gt;
        ///	&lt;string&gt;${}&lt;/string&gt;
        ///	&lt;key&gt;CFBundleIdentifier&lt;/key&gt;
        ///	&lt;string&gt;${}&lt;/string&gt;
        ///	&lt;key&gt;CFBundleInfoDictionaryVersion&lt;/key&gt;
        ///	&lt;string&gt;6.0&lt;/string&gt;
        ///	&lt;key&gt;CFBundleName&lt;/key&gt;
        ///	&lt;string&gt;${}&lt;/st [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InfoPlist {
            get {
                return ResourceManager.GetString("InfoPlist", resourceCulture);
            }
        }
        
        internal static byte[] libmonobjc_10_5 {
            get {
                object obj = ResourceManager.GetObject("libmonobjc_10_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] libmonobjc_10_6 {
            get {
                object obj = ResourceManager.GetObject("libmonobjc_10_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOMC model &apos;{0}&apos; is up-to-date..
        /// </summary>
        internal static string MomcModelUpToDate {
            get {
                return ResourceManager.GetString("MomcModelUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // 
        ///// This file is part of Monobjc, a .NET/Objective-C bridge
        ///// Copyright (C) 2007-2010 - Laurent Etiemble
        ///// 
        ///// Monobjc is free software: you can redistribute it and/or modify
        ///// it under the terms of the GNU Lesser General Public License as published
        ///// by the Free Software Foundation, either version 3 of the License, or
        ///// any later version.
        ///// 
        ///// Monobjc is distributed in the hope that it will be useful,
        ///// but WITHOUT ANY WARRANTY; without even the implied warranty of
        ///// MERCHANTABILITY or FITNESS  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string monobjc_h {
            get {
                return ResourceManager.GetString("monobjc_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No dictionary found in the command&apos;s result..
        /// </summary>
        internal static string NoDictionaryFound {
            get {
                return ResourceManager.GetString("NoDictionaryFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more errors occurred during the parsing..
        /// </summary>
        internal static string ParsingError {
            get {
                return ResourceManager.GetString("ParsingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more errors occurred during the processing..
        /// </summary>
        internal static string ProcessingError {
            get {
                return ResourceManager.GetString("ProcessingError", resourceCulture);
            }
        }
        
        internal static byte[] PropertyList_Dtd {
            get {
                object obj = ResourceManager.GetObject("PropertyList_Dtd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] runtime_10_5 {
            get {
                object obj = ResourceManager.GetObject("runtime_10_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] runtime_10_6 {
            get {
                object obj = ResourceManager.GetObject("runtime_10_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string ValueDescriptionFormat {
            get {
                return ResourceManager.GetString("ValueDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XIB compilation failed..
        /// </summary>
        internal static string XibCompilationFailed {
            get {
                return ResourceManager.GetString("XibCompilationFailed", resourceCulture);
            }
        }
    }
}
