// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace Monobjc.Tools.Generator.Model {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("doxygenindex", Namespace="", IsNullable=false)]
    public partial class DoxygenType {
        
        private string versionField;
        
        private CompoundType[] compoundField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("compound", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CompoundType[] compound {
            get {
                return this.compoundField;
            }
            set {
                this.compoundField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CompoundType {
        
        private string refidField;
        
        private CompoundKind kindField;
        
        private string nameField;
        
        private MemberType[] memberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string refid {
            get {
                return this.refidField;
            }
            set {
                this.refidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CompoundKind kind {
            get {
                return this.kindField;
            }
            set {
                this.kindField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("member", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MemberType[] member {
            get {
                return this.memberField;
            }
            set {
                this.memberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum CompoundKind {
        
        /// <remarks/>
        @class,
        
        /// <remarks/>
        @struct,
        
        /// <remarks/>
        union,
        
        /// <remarks/>
        @interface,
        
        /// <remarks/>
        protocol,
        
        /// <remarks/>
        category,
        
        /// <remarks/>
        exception,
        
        /// <remarks/>
        file,
        
        /// <remarks/>
        @namespace,
        
        /// <remarks/>
        group,
        
        /// <remarks/>
        page,
        
        /// <remarks/>
        example,
        
        /// <remarks/>
        dir,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MemberType {
        
        private string refidField1;
        
        private MemberKind kindField1;
        
        private string nameField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string refid {
            get {
                return this.refidField1;
            }
            set {
                this.refidField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MemberKind kind {
            get {
                return this.kindField1;
            }
            set {
                this.kindField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField1;
            }
            set {
                this.nameField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum MemberKind {
        
        /// <remarks/>
        define,
        
        /// <remarks/>
        property,
        
        /// <remarks/>
        @event,
        
        /// <remarks/>
        variable,
        
        /// <remarks/>
        typedef,
        
        /// <remarks/>
        @enum,
        
        /// <remarks/>
        enumvalue,
        
        /// <remarks/>
        function,
        
        /// <remarks/>
        signal,
        
        /// <remarks/>
        prototype,
        
        /// <remarks/>
        friend,
        
        /// <remarks/>
        dcop,
        
        /// <remarks/>
        slot,
    }
}
