// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace Monobjc.Tools.Generator.Model {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Framework {
        
        private string nameField;
        
        private string usingsField;
        
        private string assemblyField;
        
        private DocumentOrigin sourceField;
        
        private PageStyle styleField;
        
        private string pathField;
        
        private FrameworkType[] typesField;
        
        private FrameworkClass[] classesField;
        
        private FrameworkProtocol[] protocolsField;
        
        private FrameworkStructure[] structuresField;
        
        private FrameworkEnumeration[] enumerationsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string usings {
            get {
                return this.usingsField;
            }
            set {
                this.usingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string assembly {
            get {
                return this.assemblyField;
            }
            set {
                this.assemblyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DocumentOrigin source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValue(PageStyle.Cocoa)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PageStyle style {
            get {
                return this.styleField;
            }
            set {
                this.styleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Type", IsNullable=false)]
        public FrameworkType[] Types {
            get {
                return this.typesField;
            }
            set {
                this.typesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Class", IsNullable=false)]
        public FrameworkClass[] Classes {
            get {
                return this.classesField;
            }
            set {
                this.classesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Protocol", IsNullable=false)]
        public FrameworkProtocol[] Protocols {
            get {
                return this.protocolsField;
            }
            set {
                this.protocolsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Structure", IsNullable=false)]
        public FrameworkStructure[] Structures {
            get {
                return this.structuresField;
            }
            set {
                this.structuresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Enumeration", IsNullable=false)]
        public FrameworkEnumeration[] Enumerations {
            get {
                return this.enumerationsField;
            }
            set {
                this.enumerationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum DocumentOrigin {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        DocSet,
        
        /// <remarks/>
        Doxygen,
        
        /// <remarks/>
        Source,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum PageStyle {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Cocoa,
        
        /// <remarks/>
        Classic,
        
        /// <remarks/>
        Doxygen,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FrameworkType : FrameworkEntity {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FrameworkType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FrameworkClass))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FrameworkProtocol))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FrameworkStructure))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FrameworkEnumeration))]
    public partial class FrameworkEntity {
        
        private FrameworkEntityType typeField;
        
        private string nameField1;
        
        private string fileField;
        
        private Patch[] patchField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public FrameworkEntityType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField1;
            }
            set {
                this.nameField1 = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValue("N/A")]
        public string File {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Patch")]
        public Patch[] Patch {
            get {
                return this.patchField;
            }
            set {
                this.patchField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum FrameworkEntityType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        E,
        
        /// <remarks/>
        P,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        T,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Patch {
        
        private DocumentType typeField1;
        
        private PatchReplace[] replaceField;
        
        private string[] changeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DocumentType type {
            get {
                return this.typeField1;
            }
            set {
                this.typeField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Replace")]
        public PatchReplace[] Replace {
            get {
                return this.replaceField;
            }
            set {
                this.replaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Change")]
        public string[] Change {
            get {
                return this.changeField;
            }
            set {
                this.changeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum DocumentType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        DocSet,
        
        /// <remarks/>
        Doxygen,
        
        /// <remarks/>
        Source,
        
        /// <remarks/>
        Html,
        
        /// <remarks/>
        Xhtml,
        
        /// <remarks/>
        Model,
        
        /// <remarks/>
        Generated,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PatchReplace {
        
        private string sourceField1;
        
        private string withField;
        
        /// <remarks/>
        public string Source {
            get {
                return this.sourceField1;
            }
            set {
                this.sourceField1 = value;
            }
        }
        
        /// <remarks/>
        public string With {
            get {
                return this.withField;
            }
            set {
                this.withField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FrameworkClass : FrameworkEntity {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FrameworkProtocol : FrameworkEntity {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FrameworkStructure : FrameworkEntity {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FrameworkEnumeration : FrameworkEntity {
    }
}
